### ISSUE TITLE
라이더 배달 수락 오류

### ISSUE THREAD

**Issue by RudySeo** [mistyblue0302/food_ordering_service#83]
## 📄 Summary
>
<img width="1560" alt="스크린샷 2024-08-11 오후 9 30 33" src="https://github.com/user-attachments/assets/0cea0efa-b490-476d-a7bb-845561d90250">

배달을 완료한 라이더 다른 주문 배달 요청 상태 주문을 수락 하는 과정에서 오류 발견
오류 수정이 필요합니다
## ✅ Tasks

- [x] 수정

## 🙋🏻 More
>
1. A 라이더 1번(주문) 요청 배달완료
2. A 라이더 2번 (주문) 요청 수락 과정에서 오류 발견
@mistyblue0302

**Comment by mistyblue0302** [comment]
@RudySeo 
저희가 처음에 배달 엔티티를 짤 때 OneToOne 관계였기 때문입니다. 한 라이더가 오직 하나의 배달과만 연관될 수 있기 때문에 여러 배달 수락이 불가능합니다. User 엔티티와 Delivery 엔티티에서 연관관계를 바꾸어 주면 다른 주문 요청에 대해서도 수락이 가능합니다.

<img width="461" alt="스크린샷 2024-08-11 오후 10 23 20" src="https://github.com/user-attachments/assets/fbce31ba-a40d-4e17-b476-50bc2ecf7685">
<img width="265" alt="스크린샷 2024-08-11 오후 10 23 35" src="https://github.com/user-attachments/assets/81a7577d-0de4-4767-bccf-c56265d94b22">

**Comment by RudySeo** [comment]
@mistyblue0302 
넵 맞습니다 erd  구조 오류나면 자주 접하는 오류라서 이슈 등록했습니다
제가 브랜치 만들어서 수정 할게요~
